// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class TracksAndArtists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TracksAndArtists));
        
        string IMigrationMetadata.Id
        {
            get { return "201503132050577_TracksAndArtists"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
